package com.emarkall.worldwidephonenumberedittext;

import java.util.Arrays;
import java.util.List;

/**
 * This class serves only as a bank of data to keep
 * all the countries with their ISO code, their area code, and
 * their name
 * @author Moreno Jn Baptiste
 */
public class CountryList {

    public static final List<Country> COUNTRIES = Arrays.asList(
            new Country("af", "Afghanistan (‫افغانستان‬‎)", 93),
            new Country("al", "Albania (Shqipëri)", 355),
            new Country("dz", "Algeria (‫الجزائر‬‎)", 213),
            new Country("as", "American Samoa", 1),
            new Country("ad", "Andorra", 376),
            new Country("ao", "Angola", 244),
            new Country("ai", "Anguilla", 1),
            new Country("ag", "Antigua and Barbuda", 1),
            new Country("ar", "Argentina", 54),
            new Country("am", "Armenia (Հայաստան)", 374),
            new Country("aw", "Aruba", 297),
            new Country("au", "Australia", 61),
            new Country("at", "Austria (Österreich)", 43),
            new Country("az", "Azerbaijan (Azərbaycan)", 994),
            new Country("bs", "Bahamas", 1),
            new Country("bh", "Bahrain (‫البحرين‬‎)", 973),
            new Country("bd", "Bangladesh (বাংলাদেশ)", 880),
            new Country("bb", "Barbados", 1),
            new Country("by", "Belarus (Беларусь)", 375),
            new Country("be", "Belgium (België)", 32),
            new Country("bz", "Belize", 501),
            new Country("bj", "Benin (Bénin)", 229),
            new Country("bm", "Bermuda", 1),
            new Country("bt", "Bhutan (འབྲུག)", 975),
            new Country("bo", "Bolivia", 591),
            new Country("ba", "Bosnia and Herzegovina (Босна и Херцеговина)", 387),
            new Country("bw", "Botswana", 267),
            new Country("br", "Brazil (Brasil)", 55),
            new Country("io", "British Indian Ocean Territory", 246),
            new Country("vg", "British Virgin Islands", 1),
            new Country("bn", "Brunei", 673),
            new Country("bg", "Bulgaria (България)", 359),
            new Country("bf", "Burkina Faso", 226),
            new Country("bi", "Burundi (Uburundi)", 257),
            new Country("kh", "Cambodia (កម្ពុជា)", 855),
            new Country("cm", "Cameroon (Cameroun)", 237),
            new Country("ca", "Canada", 1),
            new Country("cv", "Cape Verde (Kabu Verdi)", 238),
            new Country("bq", "Caribbean Netherlands", 599),
            new Country("ky", "Cayman Islands", 1),
            new Country("cf", "Central African Republic (République centrafricaine)", 236),
            new Country("td", "Chad (Tchad)", 235),
            new Country("cl", "Chile", 56),
            new Country("cn", "China (中国)", 86),
            new Country("cx", "Christmas Island", 61),
            new Country("cc", "Cocos (Keeling) Islands", 61),
            new Country("co", "Colombia", 57),
            new Country("km", "Comoros (‫جزر القمر‬‎)", 269),
            new Country("cd", "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)", 243),
            new Country("cg", "Congo (Republic) (Congo-Brazzaville)", 242),
            new Country("ck", "Cook Islands", 682),
            new Country("cr", "Costa Rica", 506),
            new Country("ci", "Côte d’Ivoire", 225),
            new Country("hr", "Croatia (Hrvatska)", 385),
            new Country("cu", "Cuba", 53),
            new Country("cw", "Curaçao", 599),
            new Country("cy", "Cyprus (Κύπρος)", 357),
            new Country("cz", "Czech Republic (Česká republika)", 420),
            new Country("dk", "Denmark (Danmark)", 45),
            new Country("dj", "Djibouti", 253),
            new Country("dm", "Dominica", 1),
            new Country("do", "Dominican Republic (República Dominicana)", 1),
            new Country("ec", "Ecuador", 593),
            new Country("eg", "Egypt (‫مصر‬‎)", 20),
            new Country("sv", "El Salvador", 503),
            new Country("gq", "Equatorial Guinea (Guinea Ecuatorial)", 240),
            new Country("er", "Eritrea", 291),
            new Country("ee", "Estonia (Eesti)", 372),
            new Country("et", "Ethiopia", 251),
            new Country("fk", "Falkland Islands (Islas Malvinas)", 500),
            new Country("fo", "Faroe Islands (Føroyar)", 298),
            new Country("fj", "Fiji", 679),
            new Country("fi", "Finland (Suomi)", 358),
            new Country("fr", "France", 33),
            new Country("gf", "French Guiana (Guyane française)", 594),
            new Country("pf", "French Polynesia (Polynésie française)", 689),
            new Country("ga", "Gabon", 241),
            new Country("gm", "Gambia", 220),
            new Country("ge", "Georgia (საქართველო)", 995),
            new Country("de", "Germany (Deutschland)", 49),
            new Country("gh", "Ghana (Gaana)", 233),
            new Country("gi", "Gibraltar", 350),
            new Country("gr", "Greece (Ελλάδα)", 30),
            new Country("gl", "Greenland (Kalaallit Nunaat)", 299),
            new Country("gd", "Grenada", 1),
            new Country("gp", "Guadeloupe", 590),
            new Country("gu", "Guam", 1),
            new Country("gt", "Guatemala", 502),
            new Country("gg", "Guernsey", 44),
            new Country("gn", "Guinea (Guinée)", 224),
            new Country("gw", "Guinea-Bissau (Guiné Bissau)", 245),
            new Country("gy", "Guyana", 592),
            new Country("ht", "Haiti", 509),
            new Country("hn", "Honduras", 504),
            new Country("hk", "Hong Kong (香港)", 852),
            new Country("hu", "Hungary (Magyarország)", 36),
            new Country("is", "Iceland (Ísland)", 354),
            new Country("in", "India (भारत)", 91),
            new Country("id", "Indonesia", 62),
            new Country("ir", "Iran (‫ایران‬‎)", 98),
            new Country("iq", "Iraq (‫العراق‬‎)", 964),
            new Country("ie", "Ireland", 353),
            new Country("im", "Isle of Man", 44),
            new Country("il", "Israel (‫ישראל‬‎)", 972),
            new Country("it", "Italy (Italia)", 39),
            new Country("jm", "Jamaica", 1),
            new Country("jp", "Japan (日本)", 81),
            new Country("je", "Jersey", 44),
            new Country("jo", "Jordan (‫الأردن‬‎)", 962),
            new Country("kz", "Kazakhstan (Казахстан)", 7),
            new Country("ke", "Kenya", 254),
            new Country("ki", "Kiribati", 686),
            new Country("kw", "Kuwait (‫الكويت‬‎)", 965),
            new Country("kg", "Kyrgyzstan (Кыргызстан)", 996),
            new Country("la", "Laos (ລາວ)", 856),
            new Country("lv", "Latvia (Latvija)", 371),
            new Country("lb", "Lebanon (‫لبنان‬‎)", 961),
            new Country("ls", "Lesotho", 266),
            new Country("lr", "Liberia", 231),
            new Country("ly", "Libya (‫ليبيا‬‎)", 218),
            new Country("li", "Liechtenstein", 423),
            new Country("lt", "Lithuania (Lietuva)", 370),
            new Country("lu", "Luxembourg", 352),
            new Country("mo", "Macau (澳門)", 853),
            new Country("mk", "Macedonia (FYROM) (Македонија)", 389),
            new Country("mg", "Madagascar (Madagasikara)", 261),
            new Country("mw", "Malawi", 265),
            new Country("my", "Malaysia", 60),
            new Country("mv", "Maldives", 960),
            new Country("ml", "Mali", 223),
            new Country("mt", "Malta", 356),
            new Country("mh", "Marshall Islands", 692),
            new Country("mq", "Martinique", 596),
            new Country("mr", "Mauritania (‫موريتانيا‬‎)", 222),
            new Country("mu", "Mauritius (Moris)", 230),
            new Country("yt", "Mayotte", 262),
            new Country("mx", "Mexico (México)", 52),
            new Country("fm", "Micronesia", 691),
            new Country("md", "Moldova (Republica Moldova)", 373),
            new Country("mc", "Monaco", 377),
            new Country("mn", "Mongolia (Монгол)", 976),
            new Country("me", "Montenegro (Crna Gora)", 382),
            new Country("ms", "Montserrat", 1),
            new Country("ma", "Morocco (‫المغرب‬‎)", 212),
            new Country("mz", "Mozambique (Moçambique)", 258),
            new Country("mm", "Myanmar (Burma) (မြန်မာ)", 95),
            new Country("na", "Namibia (Namibië)", 264),
            new Country("nr", "Nauru", 674),
            new Country("np", "Nepal (नेपाल)", 977),
            new Country("nl", "Netherlands (Nederland)", 31),
            new Country("nc", "New Caledonia (Nouvelle-Calédonie)", 687),
            new Country("nz", "New Zealand", 64),
            new Country("ni", "Nicaragua", 505),
            new Country("ne", "Niger (Nijar)", 227),
            new Country("ng", "Nigeria", 234),
            new Country("nu", "Niue", 683),
            new Country("nf", "Norfolk Island", 672),
            new Country("kp", "North Korea (조선 민주주의 인민 공화국)", 850),
            new Country("mp", "Northern Mariana Islands", 1),
            new Country("no", "Norway (Norge)", 47),
            new Country("om", "Oman (‫عُمان‬‎)", 968),
            new Country("pk", "Pakistan (‫پاکستان‬‎)", 92),
            new Country("pw", "Palau", 680),
            new Country("ps", "Palestine (‫فلسطين‬‎)", 970),
            new Country("pa", "Panama (Panamá)", 507),
            new Country("pg", "Papua New Guinea", 675),
            new Country("py", "Paraguay", 595),
            new Country("pe", "Peru (Perú)", 51),
            new Country("ph", "Philippines", 63),
            new Country("pl", "Poland (Polska)", 48) ,
            new Country("pt", "Portugal", 351),
            new Country("pr", "Puerto Rico", 1),
            new Country("qa", "Qatar (‫قطر‬‎)", 974),
            new Country("re", "Réunion (La Réunion)", 262),
            new Country("ro", "Romania (România)", 40),
            new Country("ru", "Russia (Россия)", 7),
            new Country("rw", "Rwanda", 250),
            new Country("bl", "Saint Barthélemy (Saint-Barthélemy)", 590),
            new Country("sh", "Saint Helena", 290),
            new Country("kn", "Saint Kitts and Nevis", 1),
            new Country("lc", "Saint Lucia", 1),
            new Country("mf", "Saint Martin (Saint-Martin (partie française))", 590),
            new Country("pm", "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)", 508),
            new Country("vc", "Saint Vincent and the Grenadines", 1),
            new Country("ws", "Samoa", 685),
            new Country("sm", "San Marino", 378),
            new Country("st", "São Tomé and Príncipe (São Tomé e Príncipe)", 239),
            new Country("sa", "Saudi Arabia (‫المملكة العربية السعودية‬‎)", 966),
            new Country("sn", "Senegal (Sénégal)", 221),
            new Country("rs", "Serbia (Србија)", 381),
            new Country("sc", "Seychelles", 248),
            new Country("sl", "Sierra Leone", 232),
            new Country("sg", "Singapore", 65),
            new Country("sx", "Sint Maarten", 1),
            new Country("sk", "Slovakia (Slovensko)", 421),
            new Country("si", "Slovenia (Slovenija)", 386),
            new Country("sb", "Solomon Islands", 677),
            new Country("so", "Somalia (Soomaaliya)", 252),
            new Country("za", "South Africa", 27),
            new Country("kr", "South Korea (대한민국)", 82),
            new Country("ss", "South Sudan (‫جنوب السودان‬‎)", 211),
            new Country("es", "Spain (España)", 34),
            new Country("lk", "Sri Lanka (ශ්‍රී ලංකාව)", 94),
            new Country("sd", "Sudan (‫السودان‬‎)", 249),
            new Country("sr", "Suriname", 597),
            new Country("sj", "Svalbard and Jan Mayen", 47),
            new Country("sz", "Swaziland", 268),
            new Country("se", "Sweden (Sverige)", 46),
            new Country("ch", "Switzerland (Schweiz)", 41),
            new Country("sy", "Syria (‫سوريا‬‎)", 963),
            new Country("tw", "Taiwan (台灣)", 886),
            new Country("tj", "Tajikistan", 992),
            new Country("tz", "Tanzania", 255),
            new Country("th", "Thailand (ไทย)", 66),
            new Country("tl", "Timor-Leste", 670),
            new Country("tg", "Togo", 228),
            new Country("tk", "Tokelau", 690),
            new Country("to", "Tonga", 676),
            new Country("tt", "Trinidad and Tobago", 1),
            new Country("tn", "Tunisia (‫تونس‬‎)", 216),
            new Country("tr", "Turkey (Türkiye)", 90),
            new Country("tm", "Turkmenistan", 993),
            new Country("tc", "Turks and Caicos Islands", 1),
            new Country("tv", "Tuvalu", 688),
            new Country("vi", "U.S. Virgin Islands", 1),
            new Country("ug", "Uganda", 256),
            new Country("ua", "Ukraine (Україна)", 380),
            new Country("ae", "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)", 971),
            new Country("gb", "United Kingdom", 44),
            new Country("us", "United States", 1),
            new Country("uy", "Uruguay", 598),
            new Country("uz", "Uzbekistan (Oʻzbekiston)", 998),
            new Country("vu", "Vanuatu", 678),
            new Country("va", "Vatican City (Città del Vaticano)", 39),
            new Country("ve", "Venezuela", 58),
            new Country("vn", "Vietnam (Việt Nam)", 84),
            new Country("wf", "Wallis and Futuna", 681),
            new Country("eh", "Western Sahara (‫الصحراء الغربية‬‎)", 212),
            new Country("ye", "Yemen (‫اليمن‬‎)", 967),
            new Country("zm", "Zambia", 260),
            new Country("zw", "Zimbabwe", 263),
            new Country("ax", "Åland Islands", 358));
}
